### PR TITLE
rework string table

### PR DESCRIPTION
**Pull request by archaistvolts**
Use a single StringArrayHashMap and only dupe tags when not found.

---

This is an attempt to simplify the string table and reduce allocations.  While make_site is a one off program and a few extra allocations don't really matter, I think this is a still nice improvement which may even speed things up.

Instead of duping every tag key and value, we now only dupe when not found in the string table.  And when we didn't find a highway, any extra tags are freed and the string table is shrunk back to its previous size.

I've checked that lint.sh doesn't show any leaks and the web app seems to be ok.  I"ve also checked that www/map_data.json and output/map_data.bin have the same sizes as (7k and 8.7k) they did before these changes.  But I'm not very familiar with the codebase so please look this over carefully.

### CODE REVIEW

**Comment by archaistvolts** [comment]
Oh, something I wanted to share.  You might use chrome (i use ungoogled chromium) and the [C/C++ DevTools Support (DWARF) extension](https://chromewebstore.google.com/detail/cc++-devtools-support-dwa/pdcpmagijalfljmkmjngeonclgbbannb) for debugging the web app.  

I know you've started working on a native app which shows stack traces.  But here's how a stack trace looks for a bug I had while working on this PR:
Screenshot

Unfortunately, I haven't figured out how make clicking on the .zig links work.  But atleast it shows a nice trace.

Anyway thanks for the great content and happy hacking!

**Comment by sphaerophoria** [comment]
Clever! I've made some changes, because this is my project and I can do what I want, but I like the change. I think we can transition the "StringTable" into something that generically supports rollback, and the WayCache is in charge of where to roll back to. I think that keeps the WayCache responsibility the way it is, and reduces the complexity in the root xml callback areas

Please see https://github.com/sphaerophoria/sphmap/commit/79df0a1452038dd43e9d5f96b7e4b175c83acef1 and let me know if you're happy with your name staying as author here. If I've done something you'd prefer to not have deceptively marked with your name I can change the author to me and tag you as the original implementer in the commit message.

While I'm here, comparing performance of before and after, since this is advertised as a performance change (although I would take it without...)
```
Benchmark 1 (3 runs): ./zig-out/bin/make_site --input-www www --output output --index-wasm ./zig-out/bin/index.wasm --osm-data ./res/planet_-123.534,49.109_-122.87,49.374.osm
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          14.2s  ±  164ms    14.0s  … 14.3s           0 ( 0%)        0%
  peak_rss            224MB ±  279KB     223MB …  224MB          0 ( 0%)        0%
  cpu_cycles         27.2G  ±  185M     27.0G  … 27.3G           0 ( 0%)        0%
  instructions       60.6G  ±  107M     60.5G  … 60.7G           0 ( 0%)        0%
  cache_references    333M  ± 4.22M      329M  …  337M           0 ( 0%)        0%
  cache_misses       64.8M  ± 4.82M     59.4M  … 68.7M           0 ( 0%)        0%
  branch_misses      65.5M  ±  592K     65.0M  … 66.1M           0 ( 0%)        0%
Benchmark 2 (3 runs): ./zig-out/bin/make_site_pr1 --input-www www --output output --index-wasm ./zig-out/bin/index.wasm --osm-data ./res/planet_-123.534,49.109_-122.87,49.374.osm
  measurement          mean ± σ            min … max           outliers         delta
  wall_time          8.75s  ±  131ms    8.60s  … 8.85s           0 ( 0%)        ⚡- 38.2% ±  2.4%
  peak_rss            202MB ±  109KB     202MB …  203MB          0 ( 0%)        ⚡-  9.4% ±  0.2%
  cpu_cycles         24.6G  ±  123M     24.4G  … 24.7G           0 ( 0%)        ⚡-  9.5% ±  1.3%
  instructions       59.1G  ± 35.2M     59.1G  … 59.2G           0 ( 0%)        ⚡-  2.4% ±  0.3%
  cache_references    197M  ± 4.53M      192M  …  201M           0 ( 0%)        ⚡- 40.7% ±  3.0%
  cache_misses       62.4M  ± 6.51M     56.3M  … 69.2M           0 ( 0%)          -  3.7% ± 20.0%
  branch_misses      60.7M  ± 2.78M     59.1M  … 63.9M           0 ( 0%)          -  7.2% ±  7.0%

```
40% improvement is crazy.

**Comment by sphaerophoria** [comment]
> Oh, something I wanted to share. You might use chrome (i use ungoogled chromium) and the [C/C++ DevTools Support (DWARF) extension](https://chromewebstore.google.com/detail/cc++-devtools-support-dwa/pdcpmagijalfljmkmjngeonclgbbannb) for debugging the web app.

I had tried using chromium's debug tools and couldn't get it working, but the c++ devtools is likely the piece I was missing. Thanks for the tip!

**Comment by archaistvolts** [comment]
> Please see [79df0a1](https://github.com/sphaerophoria/sphmap/commit/79df0a1452038dd43e9d5f96b7e4b175c83acef1) and let me know ...

Looks good!  Thanks for cleaning up my changes and sharing the benchmark.  I'm surprised and glad to hear its 40% faster.

**Pull request closed without merging**
